plugins {
	id 'org.springframework.boot' version '3.5.3' apply false
	id 'io.spring.dependency-management' version '1.1.7' apply false
}

allprojects {
	group = 'com.mokakbob'
	version = '0.0.1-SNAPSHOT'

	repositories {
		mavenCentral()
		maven { url "https://jitpack.io" }
	}
}

subprojects {
	apply plugin: 'java'
	apply plugin: 'org.springframework.boot'
	apply plugin: 'io.spring.dependency-management'

	java {
		toolchain {
			languageVersion = JavaLanguageVersion.of(17)
		}
	}

	configurations {
		compileOnly {
			extendsFrom annotationProcessor
		}
	}

	dependencies {
		constraints {
			implementation('com.fasterxml.jackson.core:jackson-core:2.19.1')
			implementation('com.fasterxml.jackson.core:jackson-databind:2.19.1')
			implementation('com.fasterxml.jackson.core:jackson-annotations:2.19.1')
		}

		implementation 'org.springframework.boot:spring-boot-starter'
		testImplementation 'org.springframework.boot:spring-boot-starter-test'
		testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

		//H2 DB
		runtimeOnly 'com.h2database:h2'

		// mysql
		implementation 'com.mysql:mysql-connector-j:8.0.33'

		// Lombok 공통
		compileOnly 'org.projectlombok:lombok:1.18.32'
		annotationProcessor 'org.projectlombok:lombok:1.18.32'
		testCompileOnly 'org.projectlombok:lombok:1.18.32'
		testAnnotationProcessor 'org.projectlombok:lombok:1.18.32'


		testImplementation platform('org.junit:junit-bom:5.10.0')
		testImplementation 'org.junit.jupiter:junit-jupiter'
	}

	tasks.named('test') {
		useJUnitPlatform()
	}

	// 모든 모듈에서 일반 jar(plain) 생성을 비활성화 (실행 오류 방지)
	jar { enabled = false }

	// core(도메인) 모듈 등은 라이브러리로서의 jar가 필요하므로 예외 처리
	if (project.name in ["mokakbob-core", "mokakbob-kafka", "mokakbob-redis"]) {
		jar { enabled = true }
	}

	// 실행 모듈 bootJar 활성화 확인
	if (project.name in ["mokakbob-api", "mokakbob-consumer", "mokakbob-batch"]) {
		bootJar { enabled = true }
	}
}
