global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'mokakbob-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'mokakbob-api:8080'

  - job_name: 'mokakbob-consumer'
    metrics_path: '/actuator/metrics'
    static_configs:
      - targets:
          - 'mokakbob-consumer:8080'

  - job_name: 'mokakbob-batch'
    metrics_path: '/actuator/metrics'
    static_configs:
      - targets:
          - 'mokakbob-batch:8080'

  - job_name: 'redis'
    static_configs:
      - targets:
          - 'redis-exporter:9121'
